apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gzknqtgfh-python
  janus-idp.io/tekton: gzknqtgfh-python
  backstage.io/kubernetes-id: gzknqtgfh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gzknqtgfh-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
